spring:
  application:
    name: gateway
  # 'config' must be a direct child of 'spring', not 'cloud'
  config:
    import: "configserver:http://localhost:8888"
  cloud:
    config:
      fail-fast: true
  profiles:
    active: STAGE
